name: Defect Report
description: File a report for a defect.
title: "[Defect]: "
labels: ["bug", "defect", "triage"]
projects: []
assignees: []
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this defect report!
  - type: textarea
    id: symptoms
    attributes:
      label: Symptoms
      description: Describe what went wrong, along with the steps to reproduce it.
      placeholder: I did this and that, and this problem happened.
      value: ""
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead.
      placeholder: I expected this to happen instead.
      value: ""
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of dolfin are you using?
      options:
        - 3.0.0 (latest release)
        - 2.0.0
        - 1.0.0
        - main
        - devel
        - (other)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - (any)
        - (other)
      default: 5
    validations:
      required: true
  - type: dropdown
    id: oses
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Android
        - Linux
        - MacOS
        - Windows
        - iOS
        - iPadOS
        - (any)
        - (other)
      default: 7
    validations:
      required: true
  - type: checkboxes
    id: agreetococ
    attributes:
      label: Code Of Conduct
      description: By submitting this report, you agree to follow the [Code of Conduct of dolfin](https://github.com/pettarin/dolfin?tab=coc-ov-file).
      options:
        - label: I agree to follow the Code of Conduct of dolfin
          required: true
  - type: upload
    id: screenshotsorvideos
    attributes:
      label: Upload Screenshots/Videos
      description: If possible, please upload screenshots and/or videos to help explain the problem.
    validations:
      required: false

